version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - vateliermongo:/data/db
    restart: unless-stopped
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
  srv1:
    build: ./product-service/
    ports:
      - 3000:3000
    depends_on:
      - db
      - rabbit
    restart: unless-stopped
  srv2:
      build: ./order-service/
      ports:
        - 3001:3000
      depends_on:
        - db
        - rabbit
      restart: unless-stopped
  srv3:
      build: ./email-service/
      ports:
        - 3002:3000
      depends_on:
        - rabbit
      restart: unless-stopped

volumes:
  vateliermongo: